hub:
  enabled: true
  default-entry: /hubDashboard
  menu-group: hub

iot:
  enabled: false
  require-mqtt: false
  require-influx: false
  require-ota: false
  default-entry: /product
  menu-group: iot
