hub:
  enabled: true
  default-entry: /hubDashboard
  menu-group: hub

iot:
  enabled: true
  require-mqtt: true
  require-influx: true
  require-ota: true
  default-entry: /product
  menu-group: iot
